version: '3.8'

services:
  backend:
    build: .
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - PORT=9000
      - MONGODB_URI=mongodb://mongo:27017/devforge
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key
      - SESSION_SECRET=your-super-secret-session-key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - workspace-data:/workspace-data
      - ./logs:/usr/src/app/logs
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=devforge
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
  redis-data:
  workspace-data:
